name: Desplegar
 
on:
  workflow_dispatch:
  push:
    branches:
      - release
 
jobs:
  vpn_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  
 
      - name: Configurar la VPN
        working-directory: .github/workflows
        run: |
          sudo apt-get update && sudo apt-get install -y openvpn openvpn-systemd-resolved
          echo "${{ secrets.VPN_CA }}" | base64 --decode > ca.crt
          echo "${{ secrets.VPN_USERNAME }}" > credenciales.txt
          echo "${{ secrets.VPN_PASSWORD }}" >> credenciales.txt
          sed -i "s/REPLACE_VPN_IP/${{ secrets.VPN_IP }}/" vpn-pve.conf
          sed -i "s/REPLACE_VPN_PORT/${{ secrets.VPN_PORT }}/" vpn-pve.conf 
 
      - name: Connect to VPN
        working-directory: .github/workflows      
        run: sudo openvpn --config vpn-pve.conf --daemon --log openvpn.log 
 
      - name: Wait for VPN to establish
        run: sleep 10
 
      - name: Test Connection
        working-directory: .github/workflows
        run: sudo cat openvpn.log 
 
      - name: Test Connection
        run: ping -c 2 192.168.59.104
 
      - name: Run remote script
        working-directory: .github/workflows      
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_ID_RSA }}

        run: |
            echo "$SSH_PRIVATE_KEY" > ./id_rsa
            chmod 600 ./id_rsa
            ssh -i ./id_rsa -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'rm -rf speakly'
            ssh -i ./id_rsa -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'mkdir -p speakly'
            ssh -i ./id_rsa -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'git clone https://github.com/speakly-project/deployment-project.git /speakly/deployment-project'
            ssh -i ./id_rsa -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'chmod 777 -R /speakly/deployment-project'
            ssh -i ./id_rsa -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'cd /speakly/deployment-project ; git fetch --all ; git checkout -B feat/actions origin/feat/actions'
            ssh -i ./id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'bash -c "cat >> /speakly/deployment-project/environments/.env.prod << EOF

            # añadido por actions
            MYSQL_ROOT_PASSWORD_BANK=${{ secrets.DB_BANK_PWD }}
            MYSQL_ROOT_PASSWORD_STORE=${{ secrets.DB_STORE_PWD }}
            CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}
            CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_KEY }}
            CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_SECRET }}

            EOF"'
            ssh -i ./id_rsa -o StrictHostKeyChecking=no -t ${{ secrets.SERVER_USERNAME }}@192.168.59.104 'sudo /speakly/deployment-project/deploy.sh prod 2>&1'